"""add ats analysis fields

Revision ID: 737d12f1a6f8
Revises: 90f45402ddb5
Create Date: 2026-05-20 14:13:31.580809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '737d12f1a6f8'
down_revision: Union[str, Sequence[str], None] = '90f45402ddb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('resumes', sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('resumes', sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'missing_skills')
    op.drop_column('resumes', 'skills')
    op.drop_column('resumes', 'ats_score')
    # ### end Alembic commands ###
