"""add parsed_text to resumes

Revision ID: 90f45402ddb5
Revises: 9b36ce5189c2
Create Date: 2026-05-20 13:50:40.593139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90f45402ddb5'
down_revision: Union[str, Sequence[str], None] = '9b36ce5189c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('parsed_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'parsed_text')
    # ### end Alembic commands ###
