"""add ai feedback to resumes

Revision ID: 9b9fa21434f4
Revises: 737d12f1a6f8
Create Date: 2026-05-20 14:31:24.666873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b9fa21434f4'
down_revision: Union[str, Sequence[str], None] = '737d12f1a6f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('ai_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'ai_feedback')
    # ### end Alembic commands ###
